### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by chandu0101** [chandu0101/sri#1]
# Mobile
- [ ] fix fastOptJS output https://github.com/facebook/react-native/issues/465
# Web
- [ ] design web-examples demo
- [ ] add more components
# Relay
- [ ] write non trivial app in relay 
- [x] mutations not working in `fullOptJS` mode - https://github.com/scala-js/scala-js/issues/1902
# Misc
- [ ] more documentation
- [ ] test cases
- [ ] sri-cli (to bootstrap sri projects)
- [ ] provide template projects (relay)

**Comment by chandu0101** [comment]
lets create individual issues if required :)
